[package]
name = "dash_game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.11.3", default-features = false }
encase = "0.6.1"
pollster = "0.3.0"
wgpu = "0.17.1"
winit = "0.28.7"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
